language: csharp

dotnet: 2.1.4
sudo: false

env:
    global:
        - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
    - dotnet build GraphStructure.sln -c Release
    - dotnet test -c Release --no-build Test/Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
        - bash <(curl -s https://codecov.io/bash)

deploy:
    skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $TRAVIS_TAG
    on:
        tags: true
        #branch: master