version: 0.2.{build}
image: Visual Studio 2017
dotnet_csproj:
  version: "{version}"
  package_version: "{version}"
before_build:
  - dotnet restore
build:
  verbosity: normal
  # publish_nuget: true
after_build:
  - dotnet pack GraphStructure -v=n /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: E6iV/0EWXnyFgOzUzukLUvyrGzfbwUVPkPS/D3mYRW1+PF9LzF0SW10RVH7uskOH
  artifact: /.*\.nupkg/
  on:
    #appveor_repo_tag: true
    branch: master