version: 0.1.1-alpha.{build}
image: Visual Studio 2017
dotnet_csproj:
  package_version: "{version}"
before_build:
- cmd: dotnet restore
build:
  verbosity: normal
  # publish_nuget: true
after_build:
- cmd: dotnet pack GraphStructure -v=n /p:Configuration=Release
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: 4HWYue95aIcpxcp09bhEMf+3D6JHfKP+dQbSxf5ba0FvN1NK+3W7KWKi0YZZBjAd
  artifact: /.*\.nupkg/
  on:
    #appveor_repo_tag: true
    branch: master