version: 0.2.{build}
image: Visual Studio 2017
dotnet_csproj:
  version: "{version}"
  package_version: "{version}"
before_build:
  - choco install "msbuild-sonarqube-runner" -y
  - dotnet restore
  - SonarQube.Scanner.MSBuild.exe begin /k:"GraphStructure" /d:sonar.organization="a1essandro-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="d613893cd57bdd37b5fc913e5e3b5e0c7b977786"
build:
  verbosity: normal
  # publish_nuget: true
after_build:
  - SonarQube.Scanner.MSBuild.exe end /d:sonar.login="d613893cd57bdd37b5fc913e5e3b5e0c7b977786"
  - dotnet pack GraphStructure -v=n /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: 4HWYue95aIcpxcp09bhEMf+3D6JHfKP+dQbSxf5ba0FvN1NK+3W7KWKi0YZZBjAd
  artifact: /.*\.nupkg/
  on:
    #appveor_repo_tag: true
    branch: master